config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :posts do
    resources :comments
  end
resources :sessions, only: [:new, :create, :destroy]
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
 get 'logout', to: 'sessions#destroy'
  end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
    has_many :likes, dependent: :destroy
    has_secure_password
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, 
    format: { with: VALID_EMAIL_REGEX }
    before_save { self.email = email.downcase }    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
   helper_method :current_user, :logged_in?
   def already_liked?
     Like.where(user_id: current_user.id, article_id:
     params[:article_id]).exists?
   end
  def current_user
       @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
       !!current_user
  end
  
  def require_user
      if !logged_in?
       flash[:error] = "You must be logged in to perform that action"
       redirect_to root_path
      end
   end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :comment))
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:show, :update, :edit, :destroy]

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def edit	
	end

	def destroy
		@post.destroy

		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content)
	end

	def find_post
		@post = Post.find(params[:id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
 end
  def create
   user = User.find_by_email(params[:email])
   if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path , notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
 end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_user, only: [:edit,:update]
    def index
      @users = User.paginate(page: params[:page], per_page: 5)
    end
    def new
      @user = User.new
    end
    def show
      @user = User.find(params[:id])
     end
    def create
      @user = User.new(user_params)
      if @user.save
       flash[:success] = "Welcome to the alpha blog #{@user.username}"
       redirect_to posts_path
      else
       render 'new'
      end
     end
     def edit
      @user = User.find(params[:id])
     end
     def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:success] = "Your account was updated successfully"
        redirect_to posts_path
      else
        render 'edit'
      end
      end
    private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="box">
	<article class="media">
		<div class="media-content">
			<div class="content">
				<p>
					<strong><%= comment.name %>: </strong>
					<%= comment.comment %>
				</p>
			</div>
		</div>


		<%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: { confirm: "Are you sure?" } %>
	</article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
<div class="field">
	<div class="control">
		<%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
	</div>
</div>

<div class="field">
	<div class="control">
		<%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
	</div>
</div>

<%= f.button :submit, class: 'button is-primary' %>
<% end %>

app/views/home/index.html.erb
<% if current_user %>

 <%= link_to 'Log Out', logout_path %>
<% else %>
 <%= link_to 'Sign Up', signup_path %> or
 <%= link_to 'Log In', login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basic Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-info is-small">
      <!-- Hero head: will stick at the top -->
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to 'List Blog', posts_path, class: "navbar-item" %>
              <span class="navbar-burger" data-target="navbarMenuHeroA">
                <span></span>
                <span></span>
                <span></span>
              </span>
            </div>
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <%= link_to 'Create New Post', new_post_path, class: "navbar-item" %>
              </div>
            </div>
          </div>
        </nav>
      </div>

      <!-- Hero content: will be in the middle -->
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <%= yield :page_title %>
          </h1>
        </div>
      </div>
    </section>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
	<%= simple_form_for @post do |f| %>
	<div class="field">
		<div class="control">
			<%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
		</div>
	</div>

	<div class="field">
		<div class="control">
			<%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
		</div>
	</div>

	<%= f.button :submit, class: 'button is-primary' %>
	<% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title, "Index" %>

<section class="section">
	<div class="container">
		<% @posts.each do |post| %>
			<div class="card">
				<div class="card-content">
					<div class="media">
						<div class="media-content">
							<p class="title is-4">
								<%= link_to post.title, post %>
							</p>
						</div>
					</div>
					<div class="content">
						<%= post.content %>
					</div>
					<!-- <div class="comment-count">
						<span class="tag is-rounded">
							<% #comment counts %>
						</span>
					</div> -->
				</div>
			</div>
		<% end %>
	</div>
</section>

app/views/posts/new.html.erb
<% content_for :page_title, "Create a new post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section">
	<div class="container">
		<nav class="level">
			<!-- Left side -->
			<div class="level-left">
				<p class="level-left">
					<strong>Actions</strong>
				</p>
			</div>

			<!-- Right side -->
			<div class="level-right">
				<p class="level-item">
					<%= link_to "Edit", edit_post_path(@post), class: "button" %>
				</p>
				<p class="level-item">
					<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?"}, class: "button is-danger" %>
				</p>
			</div>
		</nav>
		<hr />
		<div class="content">
			<%= @post.content %>
		</div>
	</div>
</section>

<section class="section comments">
	<div class="container">
		<h2 class="subtitle is-5">
			<strong><%= @post.comments.count %> Comments</strong>
			<%= render	@post.comments %>
			<div class="comment-form">
				<hr />
				<h3 class="subtitle is-3">Leave a reply</h3>
				<%= render 'comments/form' %>
			</div>
		</h2>
	</div>
</section>

app/views/shared/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
          <small>Created by: <%= article.user.username if article.user %>,
                    <%= time_ago_in_words(article.created_at) %> ago,
                    last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
        <div class="article-actions">
        <p><%= article.likes.count %> <%= (article.likes.count) == 1 ? 'Like' : 'Likes'%></p>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
        </div>
        <div class="comment-count">
            <span class="tag is-rounded"><%= article.comments.count %> comments</span>
          </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this object from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1 bg-success">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :username %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :email %>
   </div>
   <div class="col-sm-8">
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :password %>
   </div>
   <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
   </div>
  </div>  
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
   </div>
  </div>
<% end %>
  <div class="col-xs-4 col-xs-offset-2">
  [ <%= link_to 'Cancel request and Return to Articles Listing', posts_path %> ]
  </div> 
 </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit User Account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>
<div align="center"> 
 <% @users.each do |user| %>
  <ul class="listing">
   <div class="row">
    <div class="well col-md-4 col-md-offset-4">
     <li><%= link_to gravatar_for(user), user_path(user) %></li>
     <li class="article-title"><%= link_to user.username, user_path(user) %></li>
     <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
    </div>
   </div>
  </ul>
 <% end %>
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
 <div class="col-md-4 col-md-offset-5 center">
  <%= gravatar_for @user, size: 150 %>
 </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<%= render 'shared/article', obj: @user.articles %>